on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup update --no-self-update
